// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBw4604b_Ww_SkbXdSqyRvgk6iv2Nmxg',
    appId: '1:1048229753879:web:467ff9be8a15f412295852',
    messagingSenderId: '1048229753879',
    projectId: 'zspeed',
    authDomain: 'zspeed.firebaseapp.com',
    databaseURL: 'https://zspeed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zspeed.firebasestorage.app',
    measurementId: 'G-8HH98CBKHL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0QJTJfslineGhDk-fp0X6eWvMBEqujtA',
    appId: '1:1048229753879:ios:45a611050e88f67d295852',
    messagingSenderId: '1048229753879',
    projectId: 'zspeed',
    databaseURL: 'https://zspeed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zspeed.firebasestorage.app',
    iosClientId: '1048229753879-rn5s9b34asg45ka1fh9u7iuo923v79a9.apps.googleusercontent.com',
    iosBundleId: 'com.zspeed.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvj9PtLPUn34yed46BEItxOxuBydoT8Z0',
    appId: '1:1048229753879:android:6ae82e08e1359987295852',
    messagingSenderId: '1048229753879',
    projectId: 'zspeed',
    databaseURL: 'https://zspeed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zspeed.firebasestorage.app',
  );

}